slogan: "99 little bugs in the code..."

show_heart: true

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    # icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    # icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    # icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    # icon: "fa fa-user"
  # - title: RSS
  #   url: atom.xml
  #   intro: "Subscribe me."
  #   # icon: "fa fa-user"

links:
  - title: "My Github"
    url: https://github.com/tingkaiwu
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My LinkedIn"
    url: https://www.linkedin.com/in/tingkai-wu
    intro: "My Linkin account."
    icon: "fa fa-linkedin"
  - title: "My Profile"
    url: http://tingkaiwu.com/about/
    intro: "My profile."
    icon: "fa fa-file-text"
  - title: "My Email"
    url: mailto:tingkaiwuu@gmail.com
    intro: "My email address."
    icon: "fa fa-envelope"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname:


# Analytics (change to yours)
google_analytics:
  enable: true
  siteid: UA-169367660-1
baidu_tongji:
  enable: false
  siteid: 

# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
